import type { ReportCpInlineCandidatesInput } from "@/schemas/domain-component-inputs"

export const reportCpInlineCandidatesFixture: ReportCpInlineCandidatesInput = {
  title: "Recommended CP × Inline Candidates",
  subtitle:
    "当前 Generation 内按同一 Wafer 配对的趋势候选；打开一行进入选中组合的拟合证据。",
  cpParameterOptions: ["kelvinS", "VGSTX3", "VGSTX2"],
  inlineParameterOptions: [
    "AMY-SN080T24-TR-ETCH-DEF-02",
    "AME-SN080T24-CT-ET2-AEI-69",
  ],
  filters: {
    cpParameter: null,
    inlineParameter: null,
    level: "RECOMMENDED",
    direction: null,
    minN: null,
  },
  items: [
    {
      experimentGroupId: "CPX-S03||Pre clean",
      stepLabel: "CPX-S03",
      factorLabel: "Pre clean",
      cpParameter: "kelvinS",
      inlineParameter: "AMY-SN080T24-TR-ETCH-DEF-02",
      pairedCount: 4,
      assignedWaferCount: 4,
      pairedCoverage: 1,
      direction: "POSITIVE",
      spearman: 1,
      rSquared: 0.994768,
      cpResponse: 0.00006,
      cpSpread: 0.00012,
      score: 99.8169,
      level: "HIGH_TREND",
      sampleBand: "SMALL_SAMPLE",
      filterReason: null,
      algorithmVersion: "inline-cp/2.1.0",
    },
    {
      experimentGroupId: "CPX-S04||Screen OX",
      stepLabel: "CPX-S04",
      factorLabel: "Screen OX",
      cpParameter: "VGSTX3",
      inlineParameter: "AME-SN080T24-CT-ET2-AEI-69",
      pairedCount: 4,
      assignedWaferCount: 4,
      pairedCoverage: 1,
      direction: "POSITIVE",
      spearman: 1,
      rSquared: 0.986402,
      cpResponse: null,
      cpSpread: null,
      score: 99.5241,
      level: "HIGH_TREND",
      sampleBand: "SMALL_SAMPLE",
      filterReason: null,
      algorithmVersion: "inline-cp/2.1.0",
    },
    {
      experimentGroupId: "CPX-S04||Screen OX",
      stepLabel: "CPX-S04",
      factorLabel: "Screen OX",
      cpParameter: "VGSTX2",
      inlineParameter: "AME-SN080T24-CT-ET2-AEI-69",
      pairedCount: 4,
      assignedWaferCount: 4,
      pairedCoverage: 1,
      direction: "POSITIVE",
      spearman: 1,
      rSquared: 0.98438,
      cpResponse: null,
      cpSpread: null,
      score: 99.4533,
      level: "HIGH_TREND",
      sampleBand: "SMALL_SAMPLE",
      filterReason: null,
      algorithmVersion: "inline-cp/2.1.0",
    },
  ],
  page: 1,
  pageSize: 8,
  total: 4126,
  calculationVersion: "inline-cp/2.1.0",
  provenance: {
    classification: "redacted-real",
    source: "RND_AF01112_CP_DEMO generation 13 candidate snapshot",
    limitation: "Only the first three Backend-ranked candidates are shown.",
  },
}

export const reportCpInlineCandidatesEmptyFixture: ReportCpInlineCandidatesInput = {
  ...reportCpInlineCandidatesFixture,
  filters: {
    ...reportCpInlineCandidatesFixture.filters,
    cpParameter: "NO_MATCH",
  },
  items: [],
  total: 0,
  provenance: {
    classification: "mock",
    source: "Empty-filter scenario",
  },
}
