import { measurementFixture } from "@/components/domain/measurement.fixtures"
import { waferMapW01Fixture } from "@/components/domain/wafer-map.fixtures"
import type {
  ReportCpDataInput,
  ReportCpInlineInput,
  ReportInlineDataInput,
  ReportOverviewInput,
  ReportParameterMedianInput,
  ReportSplitTableInput,
  ReportWaferMapInput,
  ReportYieldAnalysisInput,
} from "@/schemas/domain-component-inputs"

export const reportOverviewFixture: ReportOverviewInput = {
  title: "Overview",
  subtitle: "DOE report round summary and exception entry points.",
  sourceLabel: "REPORT SNAPSHOT",
  identity: {
    product: "S0269A · Power MOSFET",
    lotId: "AF01112",
    stepCount: "18/18",
    waferCount: "25",
    summary:
      "本次 OXIDE ETCH Power DOE 共拆分 8 个 Split Group、15 个 Variant。3片 Wafer 的良率低于 99.5%，3片 Wafer 存在 CP Parameter OOS。",
  },
  metrics: [
    { label: "Fail Die", value: "8,857", detail: "of 102,475 tested", tone: "watch" },
    { label: "Defect Wafers", value: "25", detail: "3,387 total defects", tone: "watch" },
    { label: "Low Yield", value: "3", detail: "below 99.5%", tone: "bad" },
    { label: "CP OOS", value: "3", detail: "parameters with alerts", tone: "bad" },
  ],
  focusItems: [
    { label: "PW IMP dose", detail: "Current round process focus", tone: "neutral" },
    { label: "CT PH CD", detail: "CD window validation", tone: "neutral" },
    { label: "BS LTO before HDP CMP", detail: "Stack review item", tone: "neutral" },
  ],
  failGroups: [
    { label: "BVDSS", value: "14", detail: "top fail on W01", tone: "watch" },
    { label: "IDSS", value: "6", detail: "top fail on W02", tone: "neutral" },
    { label: "IGSSN1", value: "OOS", detail: "parameter alert", tone: "bad" },
  ],
  lowYieldWafers: [
    { label: "W03", value: "7.78%", detail: "split-2", tone: "bad" },
    { label: "W12", value: "23.69%", detail: "SG1 ET Depth", tone: "bad" },
    { label: "W10", value: "62.43%", detail: "LOX", tone: "watch" },
  ],
  parameterAlerts: [
    { label: "IGSSN1", value: "CPK 1.21", detail: "below review threshold", tone: "bad" },
    { label: "BVDSS", value: "LSL hit", detail: "source provisional", tone: "watch" },
    { label: "IDSS", value: "watch", detail: "distribution changed", tone: "watch" },
  ],
}

export const reportSplitTableFixture: ReportSplitTableInput = {
  title: "Wafer Split Table",
  subtitle: "Read-only report snapshot of wafer split assignment and yield.",
  sourceLabel: "REPORT SNAPSHOT",
  stageOptions: [
    "Lithography",
    "Etch",
    "Clean",
    "Oxidation",
    "Backside Process",
    "Wet Clean",
    "Baseline",
  ],
  stepOptions: [
    "TR CD",
    "TR Depth",
    "Pre clean",
    "LOX",
    "SG1 ET Depth",
    "LOX PB",
    "IPO_ET",
    "Warpage",
    "P2_ET",
    "Mesa OX Wet Dip",
    "Screen OX",
    "Post-run BSL",
  ],
  selectedStages: [],
  selectedSteps: [],
  rows: [
    {
      waferId: "W01",
      role: "BSL",
      stage: "Lithography",
      step: "TR CD",
      seq: "seq-num-001",
      recipe: "0.79um",
      condition: "0.79um",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W02",
      role: "split-1",
      stage: "Lithography",
      step: "TR CD",
      seq: "seq-num-001",
      recipe: "0.75um",
      condition: "0.75um",
      yield: 99.71,
      topFail: "Default",
      topFailCount: 6,
      tone: "good",
    },
    {
      waferId: "W03",
      role: "split-2",
      stage: "Lithography",
      step: "TR CD",
      seq: "seq-num-001",
      recipe: "0.83um",
      condition: "0.83um",
      yield: 7.78,
      topFail: "VGSTX1",
      topFailCount: 3769,
      tone: "bad",
    },
    {
      waferId: "W01",
      role: "BSL",
      stage: "Etch",
      step: "TR Depth",
      seq: "seq-num-001",
      recipe: "5um",
      condition: "5um",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W04",
      role: "split-1",
      stage: "Etch",
      step: "TR Depth",
      seq: "seq-num-001",
      recipe: "4.5um",
      condition: "4.5um",
      yield: 99.9,
      topFail: "Default",
      topFailCount: 2,
      tone: "good",
    },
    {
      waferId: "W05",
      role: "split-2",
      stage: "Etch",
      step: "TR Depth",
      seq: "seq-num-001",
      recipe: "5.5um",
      condition: "5.5um",
      yield: 99.32,
      topFail: "Default",
      topFailCount: 23,
      tone: "watch",
    },
    {
      waferId: "W01",
      role: "BSL",
      stage: "Etch",
      step: "TR Depth",
      seq: "seq-num-002",
      recipe: "5um",
      condition: "5um",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W06",
      role: "split-1",
      stage: "Etch",
      step: "TR Depth",
      seq: "seq-num-002",
      recipe: "4.75um",
      condition: "4.75um",
      yield: 99.73,
      topFail: "Default",
      topFailCount: 9,
      tone: "good",
    },
    {
      waferId: "W07",
      role: "split-2",
      stage: "Etch",
      step: "TR Depth",
      seq: "seq-num-002",
      recipe: "5.25um",
      condition: "5.25um",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 11,
      tone: "good",
    },
    {
      waferId: "W01",
      role: "BSL",
      stage: "Clean",
      step: "Pre clean",
      seq: "seq-num-001",
      recipe: "BOE 30A",
      condition: "BOE 30A",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W08",
      role: "split-1",
      stage: "Clean",
      step: "Pre clean",
      seq: "seq-num-001",
      recipe: "HF 30A",
      condition: "HF 30A",
      yield: 99.66,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W01",
      role: "BSL",
      stage: "Oxidation",
      step: "LOX",
      seq: "seq-num-001",
      recipe: "3900A",
      condition: "3900A",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W09",
      role: "split-1",
      stage: "Oxidation",
      step: "LOX",
      seq: "seq-num-001",
      recipe: "3600A",
      condition: "3600A",
      yield: 99.73,
      topFail: "Default",
      topFailCount: 9,
      tone: "good",
    },
    {
      waferId: "W10",
      role: "split-2",
      stage: "Oxidation",
      step: "LOX",
      seq: "seq-num-001",
      recipe: "4200A",
      condition: "4200A",
      yield: 62.43,
      topFail: "VGSTX1",
      topFailCount: 1005,
      tone: "bad",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Etch",
      step: "SG1 ET Depth",
      seq: "seq-num-001",
      recipe: "1.18um",
      condition: "1.18um",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W12",
      role: "split-1",
      stage: "Etch",
      step: "SG1 ET Depth",
      seq: "seq-num-001",
      recipe: "1.08um",
      condition: "1.08um",
      yield: 23.69,
      topFail: "IGSSP1",
      topFailCount: 2996,
      tone: "bad",
    },
    {
      waferId: "W13",
      role: "split-2",
      stage: "Etch",
      step: "SG1 ET Depth",
      seq: "seq-num-001",
      recipe: "1.28um",
      condition: "1.28um",
      yield: 99.68,
      topFail: "Default",
      topFailCount: 11,
      tone: "good",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Etch",
      step: "LOX PB",
      seq: "seq-num-001",
      recipe: "1500A",
      condition: "1500A",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W14",
      role: "split-1",
      stage: "Etch",
      step: "LOX PB",
      seq: "seq-num-001",
      recipe: "1200A",
      condition: "1200A",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 19,
      tone: "good",
    },
    {
      waferId: "W15",
      role: "split-2",
      stage: "Etch",
      step: "LOX PB",
      seq: "seq-num-001",
      recipe: "1000A",
      condition: "1000A",
      yield: 99.68,
      topFail: "Default",
      topFailCount: 9,
      tone: "good",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Etch",
      step: "IPO_ET",
      seq: "seq-num-001",
      recipe: "IPO Remain~2800A",
      condition: "IPO Remain~2800A",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W16",
      role: "split-1",
      stage: "Etch",
      step: "IPO_ET",
      seq: "seq-num-001",
      recipe: "IPO Remain~2500A",
      condition: "IPO Remain~2500A",
      yield: 99.68,
      topFail: "Default",
      topFailCount: 12,
      tone: "good",
    },
    {
      waferId: "W17",
      role: "split-2",
      stage: "Etch",
      step: "IPO_ET",
      seq: "seq-num-001",
      recipe: "IPO Remain~3100A",
      condition: "IPO Remain~3100A",
      yield: 99.63,
      topFail: "Default",
      topFailCount: 13,
      tone: "good",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Backside Process",
      step: "Warpage",
      seq: "seq-num-001",
      recipe: "5K + SPM 5min + SC1 5min",
      condition: "5K + SPM 5min + SC1 5min",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W18",
      role: "split-1",
      stage: "Backside Process",
      step: "Warpage",
      seq: "seq-num-001",
      recipe: "1K+Skip clean",
      condition: "1K+Skip clean",
      yield: 99.83,
      topFail: "Default",
      topFailCount: 7,
      tone: "good",
    },
    {
      waferId: "W19",
      role: "split-1",
      stage: "Backside Process",
      step: "Warpage",
      seq: "seq-num-001",
      recipe: "1K+Skip clean",
      condition: "1K+Skip clean",
      yield: 99.56,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Etch",
      step: "P2_ET",
      seq: "seq-num-001",
      recipe: "660A",
      condition: "660A",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W20",
      role: "split-1",
      stage: "Etch",
      step: "P2_ET",
      seq: "seq-num-001",
      recipe: "BSL-10%",
      condition: "BSL-10%",
      yield: 99.83,
      topFail: "Default",
      topFailCount: 5,
      tone: "good",
    },
    {
      waferId: "W21",
      role: "split-2",
      stage: "Etch",
      step: "P2_ET",
      seq: "seq-num-001",
      recipe: "BSL+10%",
      condition: "BSL+10%",
      yield: 99.71,
      topFail: "Default",
      topFailCount: 7,
      tone: "good",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Wet Clean",
      step: "Mesa OX Wet Dip",
      seq: "seq-num-001",
      recipe: "600A",
      condition: "600A",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W22",
      role: "split-1",
      stage: "Wet Clean",
      step: "Mesa OX Wet Dip",
      seq: "seq-num-001",
      recipe: "400A",
      condition: "400A",
      yield: 99.61,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W23",
      role: "split-2",
      stage: "Wet Clean",
      step: "Mesa OX Wet Dip",
      seq: "seq-num-001",
      recipe: "500A",
      condition: "500A",
      yield: 99.76,
      topFail: "Default",
      topFailCount: 10,
      tone: "good",
    },
    {
      waferId: "W11",
      role: "BSL",
      stage: "Oxidation",
      step: "Screen OX",
      seq: "seq-num-001",
      recipe: "1000C 550A",
      condition: "1000C 550A",
      yield: 99.51,
      topFail: "Default",
      topFailCount: 14,
      tone: "good",
    },
    {
      waferId: "W24",
      role: "split-1",
      stage: "Oxidation",
      step: "Screen OX",
      seq: "seq-num-001",
      recipe: "1050C 550A",
      condition: "1050C 550A",
      yield: 99.56,
      topFail: "Default",
      topFailCount: 17,
      tone: "good",
    },
    {
      waferId: "W25",
      role: "BSL",
      stage: "Baseline",
      step: "Post-run BSL",
      seq: "seq-num-001",
      recipe: "BSL",
      condition: "BSL",
      yield: 97.15,
      topFail: "Default",
      topFailCount: 71,
      tone: "watch",
    },
  ],
}

export const reportYieldAnalysisFixture: ReportYieldAnalysisInput = {
  title: "Yield Analysis",
  subtitle: "Wafer yield ranking with CP loss and condition-level detail.",
  sourceLabel: "REPORT SNAPSHOT",
  stageOptions: [
    "Lithography",
    "Etch",
    "Clean",
    "Oxidation",
    "Backside Process",
    "Wet Clean",
    "Baseline",
  ],
  stepOptions: [
    "BSL",
    "TR CD",
    "TR Depth",
    "Pre clean",
    "LOX",
    "SG1 ET Depth",
    "LOX PB",
    "IPO_ET",
    "Warpage",
    "P2_ET",
    "Mesa OX Wet Dip",
    "Screen OX",
  ],
  selectedStages: [],
  selectedSteps: [],
  thresholds: { good: 99.5, watch: 90 },
  wafers: [
    { waferId: "W03", stage: "Lithography", step: "TR CD", seq: "seq-num-002", yield: 7.78, role: "split-2", condition: "0.83um", tone: "bad" },
    { waferId: "W12", stage: "Etch", step: "SG1 ET Depth", seq: "seq-num-001", yield: 23.69, role: "split-1", condition: "1.08um", tone: "bad" },
    { waferId: "W10", stage: "Oxidation", step: "LOX", seq: "seq-num-001", yield: 62.43, role: "split-2", condition: "4200A", tone: "bad" },
    { waferId: "W25", stage: "Baseline", step: "BSL", seq: "seq-num-001", yield: 97.15, role: "BSL", condition: "BSL", tone: "watch" },
    { waferId: "W05", stage: "Etch", step: "TR Depth", seq: "seq-num-001", yield: 99.32, role: "split-2", condition: "5.5um", tone: "watch" },
    { waferId: "W11", stage: "Baseline", step: "BSL", seq: "seq-num-001", yield: 99.51, role: "BSL", condition: "BSL", tone: "good" },
    { waferId: "W14", stage: "Etch", step: "LOX PB", seq: "seq-num-001", yield: 99.51, role: "split-1", condition: "1200A", tone: "good" },
    { waferId: "W19", stage: "Backside Process", step: "Warpage", seq: "seq-num-001", yield: 99.56, role: "split-1", condition: "1K+Skip clean", tone: "good" },
    { waferId: "W24", stage: "Oxidation", step: "Screen OX", seq: "seq-num-001", yield: 99.56, role: "split-1", condition: "1050C 550A", tone: "good" },
    { waferId: "W22", stage: "Wet Clean", step: "Mesa OX Wet Dip", seq: "seq-num-001", yield: 99.61, role: "split-1", condition: "400A", tone: "good" },
    { waferId: "W01", stage: "Baseline", step: "BSL", seq: "seq-num-001", yield: 99.63, role: "BSL", condition: "BSL", tone: "good" },
    { waferId: "W07", stage: "Etch", step: "TR Depth", seq: "seq-num-001", yield: 99.63, role: "split-2", condition: "5.25um", tone: "good" },
    { waferId: "W17", stage: "Etch", step: "IPO_ET", seq: "seq-num-001", yield: 99.63, role: "split-2", condition: "IPO Remain~3100A", tone: "good" },
    { waferId: "W08", stage: "Clean", step: "Pre clean", seq: "seq-num-001", yield: 99.66, role: "split-1", condition: "HF 30A", tone: "good" },
    { waferId: "W13", stage: "Etch", step: "SG1 ET Depth", seq: "seq-num-001", yield: 99.68, role: "split-2", condition: "1.28um", tone: "good" },
    { waferId: "W15", stage: "Etch", step: "LOX PB", seq: "seq-num-001", yield: 99.68, role: "split-2", condition: "1000A", tone: "good" },
    { waferId: "W16", stage: "Etch", step: "IPO_ET", seq: "seq-num-001", yield: 99.68, role: "split-1", condition: "IPO Remain~2500A", tone: "good" },
    { waferId: "W02", stage: "Lithography", step: "TR CD", seq: "seq-num-002", yield: 99.71, role: "split-1", condition: "0.75um", tone: "good" },
    { waferId: "W21", stage: "Etch", step: "P2_ET", seq: "seq-num-001", yield: 99.71, role: "split-2", condition: "BSL+10%", tone: "good" },
    { waferId: "W06", stage: "Etch", step: "TR Depth", seq: "seq-num-001", yield: 99.73, role: "split-1", condition: "4.75um", tone: "good" },
    { waferId: "W09", stage: "Oxidation", step: "LOX", seq: "seq-num-001", yield: 99.73, role: "split-1", condition: "3600A", tone: "good" },
    { waferId: "W23", stage: "Wet Clean", step: "Mesa OX Wet Dip", seq: "seq-num-001", yield: 99.76, role: "split-2", condition: "500A", tone: "good" },
    { waferId: "W18", stage: "Backside Process", step: "Warpage", seq: "seq-num-001", yield: 99.83, role: "split-1", condition: "1K+Skip clean", tone: "good" },
    { waferId: "W20", stage: "Etch", step: "P2_ET", seq: "seq-num-001", yield: 99.83, role: "split-1", condition: "BSL-10%", tone: "good" },
    { waferId: "W04", stage: "Etch", step: "TR Depth", seq: "seq-num-001", yield: 99.9, role: "split-1", condition: "4.5um", tone: "good" },
  ],
  detailModeOptions: [
    { id: "wafer-cp-matrix", label: "Wafer x CP Matrix" },
    { id: "loss-yield", label: "Loss Yield" },
    { id: "condition-yield-comparison", label: "Condition Yield Comparison" },
  ],
  selectedDetailMode: "wafer-cp-matrix",
  matrixColumns: [
    "BVDSS",
    "IDSS",
    "IDSS_80P",
    "IDSS_100P",
    "IGSS",
    "IGSSP1",
    "IGSSN1",
    "IGSSPSC",
    "IGSSNSC",
    "VTH",
    "VGSTX1",
    "VGSTX2",
    "RDS(on)",
    "RDS_ON_4V5",
    "RDS_ON_10V",
    "VF",
    "VSD",
    "BVDS",
    "BVGSS",
    "VGS(th)",
    "gm",
    "Ciss",
    "Coss",
    "Crss",
    "Qg",
    "Qgd",
    "Qgs",
    "Td(on)",
    "Tr",
    "Td(off)",
    "Tf",
    "EAS",
    "EAR",
    "UIS",
    "Ron_sp",
    "Leak_D",
    "Leak_G",
    "VBR",
    "I_BD",
    "VDS_sat",
    "VSD_F",
    "VSD_R",
    "I_Gate_Pos",
    "I_Gate_Neg",
    "Gate_Short",
    "Drain_Short",
    "Source_Short",
    "SHORT",
    "OPEN",
    "dVGSTX",
    "dVTH",
    "dRDS",
    "dBVDSS",
    "CP_MARGIN",
    "FINAL_BIN",
  ],
  matrixRows: [
    { waferId: "W01", role: "BSL", stage: "Baseline", step: "BSL", seq: "seq-num-001", condition: "BSL", yield: 99.63, passDies: 4084, testedDies: 4099, failCounts: { SHORT: 1 }, tone: "good" },
    { waferId: "W02", role: "split-1", stage: "Lithography", step: "TR CD", seq: "seq-num-002", condition: "0.75um", yield: 99.71, passDies: 4087, testedDies: 4099, failCounts: { BVDSS: 4, IGSSP1: 1, VGSTX1: 1 }, tone: "good" },
    { waferId: "W03", role: "split-2", stage: "Lithography", step: "TR CD", seq: "seq-num-002", condition: "0.83um", yield: 7.78, passDies: 319, testedDies: 4099, failCounts: { IGSSP1: 2, VGSTX1: 3769 }, tone: "bad" },
    { waferId: "W04", role: "split-1", stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "4.5um", yield: 99.9, passDies: 4095, testedDies: 4099, failCounts: { IDSS_80P: 1, Gate_Short: 1 }, tone: "good" },
    { waferId: "W05", role: "split-2", stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "5.5um", yield: 99.32, passDies: 4071, testedDies: 4099, failCounts: { BVDSS: 2, IDSS_80P: 1, IGSSP1: 1, Gate_Short: 1 }, tone: "watch" },
    { waferId: "W06", role: "split-1", stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "4.75um", yield: 99.73, passDies: 4088, testedDies: 4099, failCounts: { BVDSS: 2 }, tone: "good" },
    { waferId: "W07", role: "split-2", stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "5.25um", yield: 99.63, passDies: 4084, testedDies: 4099, failCounts: { BVDSS: 3, Gate_Short: 1 }, tone: "good" },
    { waferId: "W08", role: "split-1", stage: "Clean", step: "Pre clean", seq: "seq-num-001", condition: "HF 30A", yield: 99.66, passDies: 4085, testedDies: 4099, failCounts: {}, tone: "good" },
    { waferId: "W09", role: "split-1", stage: "Oxidation", step: "LOX", seq: "seq-num-001", condition: "3600A", yield: 99.73, passDies: 4088, testedDies: 4099, failCounts: { BVDSS: 2 }, tone: "good" },
    { waferId: "W10", role: "split-2", stage: "Oxidation", step: "LOX", seq: "seq-num-001", condition: "4200A", yield: 62.43, passDies: 2559, testedDies: 4099, failCounts: { BVDSS: 2, VGSTX1: 1005 }, tone: "bad" },
    { waferId: "W11", role: "BSL", stage: "Baseline", step: "BSL", seq: "seq-num-001", condition: "BSL", yield: 99.51, passDies: 4079, testedDies: 4099, failCounts: { BVDSS: 4, IDSS_80P: 1, SHORT: 1 }, tone: "good" },
    { waferId: "W12", role: "split-1", stage: "Etch", step: "SG1 ET Depth", seq: "seq-num-001", condition: "1.08um", yield: 23.69, passDies: 971, testedDies: 4099, failCounts: { BVDSS: 3, IGSSP1: 2996, IGSSN1: 1, IGSSPSC: 97, IGSSNSC: 1, SHORT: 2 }, tone: "bad" },
    { waferId: "W13", role: "split-2", stage: "Etch", step: "SG1 ET Depth", seq: "seq-num-001", condition: "1.28um", yield: 99.68, passDies: 4086, testedDies: 4099, failCounts: { IDSS_80P: 2 }, tone: "good" },
    { waferId: "W14", role: "split-1", stage: "Etch", step: "LOX PB", seq: "seq-num-001", condition: "1200A", yield: 99.51, passDies: 4079, testedDies: 4099, failCounts: { IDSS_100P: 1 }, tone: "good" },
    { waferId: "W15", role: "split-2", stage: "Etch", step: "LOX PB", seq: "seq-num-001", condition: "1000A", yield: 99.68, passDies: 4086, testedDies: 4099, failCounts: { BVDSS: 2, IGSSP1: 1, Gate_Short: 1 }, tone: "good" },
    { waferId: "W16", role: "split-1", stage: "Etch", step: "IPO_ET", seq: "seq-num-001", condition: "IPO Remain~2500A", yield: 99.68, passDies: 4086, testedDies: 4099, failCounts: { IGSSP1: 1 }, tone: "good" },
    { waferId: "W17", role: "split-2", stage: "Etch", step: "IPO_ET", seq: "seq-num-001", condition: "IPO Remain~3100A", yield: 99.63, passDies: 4084, testedDies: 4099, failCounts: { BVDSS: 2 }, tone: "good" },
    { waferId: "W18", role: "split-1", stage: "Backside Process", step: "Warpage", seq: "seq-num-001", condition: "1K+Skip clean", yield: 99.83, passDies: 4092, testedDies: 4099, failCounts: {}, tone: "good" },
    { waferId: "W19", role: "split-1", stage: "Backside Process", step: "Warpage", seq: "seq-num-001", condition: "1K+Skip clean", yield: 99.56, passDies: 4081, testedDies: 4099, failCounts: { BVDSS: 1, IGSSP1: 2, SHORT: 1 }, tone: "good" },
    { waferId: "W20", role: "split-1", stage: "Etch", step: "P2_ET", seq: "seq-num-001", condition: "BSL-10%", yield: 99.83, passDies: 4092, testedDies: 4099, failCounts: { BVDSS: 1, IDSS_80P: 1 }, tone: "good" },
    { waferId: "W21", role: "split-2", stage: "Etch", step: "P2_ET", seq: "seq-num-001", condition: "BSL+10%", yield: 99.71, passDies: 4087, testedDies: 4099, failCounts: { BVDSS: 2, IGSSP1: 1, SHORT: 2 }, tone: "good" },
    { waferId: "W22", role: "split-1", stage: "Wet Clean", step: "Mesa OX Wet Dip", seq: "seq-num-001", condition: "400A", yield: 99.61, passDies: 4083, testedDies: 4099, failCounts: { IGSSP1: 2 }, tone: "good" },
    { waferId: "W23", role: "split-2", stage: "Wet Clean", step: "Mesa OX Wet Dip", seq: "seq-num-001", condition: "500A", yield: 99.76, passDies: 4089, testedDies: 4099, failCounts: {}, tone: "good" },
    { waferId: "W24", role: "split-1", stage: "Oxidation", step: "Screen OX", seq: "seq-num-001", condition: "1050C 550A", yield: 99.56, passDies: 4081, testedDies: 4099, failCounts: { IGSSP1: 1 }, tone: "good" },
    { waferId: "W25", role: "BSL", stage: "Baseline", step: "BSL", seq: "seq-num-001", condition: "BSL", yield: 97.15, passDies: 3982, testedDies: 4099, failCounts: { BVDSS: 1, IGSSP1: 42, Gate_Short: 3 }, tone: "watch" },
  ],
  lossYieldRows: [
    { rank: 1, parameter: "VGSTX1", failedDieCount: 4775, pareto: 59.87, yieldLoss: 4.66, cumulativeYieldLoss: 4.66, tone: "bad" },
    { rank: 2, parameter: "IGSSP1", failedDieCount: 3050, pareto: 38.24, yieldLoss: 2.98, cumulativeYieldLoss: 7.64, tone: "bad" },
    { rank: 3, parameter: "IGSSPSC", failedDieCount: 97, pareto: 1.22, yieldLoss: 0.09, cumulativeYieldLoss: 7.73, tone: "watch" },
    { rank: 4, parameter: "BVDSS", failedDieCount: 31, pareto: 0.39, yieldLoss: 0.03, cumulativeYieldLoss: 7.76, tone: "neutral" },
    { rank: 5, parameter: "SHORT", failedDieCount: 13, pareto: 0.16, yieldLoss: 0.01, cumulativeYieldLoss: 7.77, tone: "neutral" },
    { rank: 6, parameter: "IDSS_80P", failedDieCount: 6, pareto: 0.08, yieldLoss: 0.01, cumulativeYieldLoss: 7.78, tone: "neutral" },
    { rank: 7, parameter: "IDSS_100P", failedDieCount: 1, pareto: 0.01, yieldLoss: 0, cumulativeYieldLoss: 7.78, tone: "neutral" },
    { rank: 8, parameter: "IGSSN1", failedDieCount: 1, pareto: 0.01, yieldLoss: 0, cumulativeYieldLoss: 7.78, tone: "neutral" },
    { rank: 9, parameter: "IGSSNSC", failedDieCount: 1, pareto: 0.01, yieldLoss: 0, cumulativeYieldLoss: 7.78, tone: "neutral" },
    { rank: 10, parameter: "dVGSTX", failedDieCount: 1, pareto: 0.01, yieldLoss: 0, cumulativeYieldLoss: 7.78, tone: "neutral" },
  ],
  conditionYieldRows: [
    { waferIds: ["W01", "W11", "W25"], stage: "Baseline", step: "BSL", seq: "seq-num-001", condition: "BSL", weightedYield: 98.76, medianYield: 99.51, averageYield: 98.76, minYield: 97.15, maxYield: 99.63, tone: "watch" },
    { waferIds: ["W18", "W19"], stage: "Backside Process", step: "Warpage", seq: "seq-num-001", condition: "1K+Skip clean", weightedYield: 99.7, medianYield: 99.7, averageYield: 99.7, minYield: 99.56, maxYield: 99.83, tone: "good" },
    { waferIds: ["W02"], stage: "Lithography", step: "TR CD", seq: "seq-num-002", condition: "0.75um", weightedYield: 99.71, medianYield: 99.71, averageYield: 99.71, minYield: 99.71, maxYield: 99.71, tone: "good" },
    { waferIds: ["W03"], stage: "Lithography", step: "TR CD", seq: "seq-num-002", condition: "0.83um", weightedYield: 7.78, medianYield: 7.78, averageYield: 7.78, minYield: 7.78, maxYield: 7.78, tone: "bad" },
    { waferIds: ["W04"], stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "4.5um", weightedYield: 99.9, medianYield: 99.9, averageYield: 99.9, minYield: 99.9, maxYield: 99.9, tone: "good" },
    { waferIds: ["W05"], stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "5.5um", weightedYield: 99.32, medianYield: 99.32, averageYield: 99.32, minYield: 99.32, maxYield: 99.32, tone: "watch" },
    { waferIds: ["W06"], stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "4.75um", weightedYield: 99.73, medianYield: 99.73, averageYield: 99.73, minYield: 99.73, maxYield: 99.73, tone: "good" },
    { waferIds: ["W07"], stage: "Etch", step: "TR Depth", seq: "seq-num-001", condition: "5.25um", weightedYield: 99.63, medianYield: 99.63, averageYield: 99.63, minYield: 99.63, maxYield: 99.63, tone: "good" },
    { waferIds: ["W08"], stage: "Clean", step: "Pre clean", seq: "seq-num-001", condition: "HF 30A", weightedYield: 99.66, medianYield: 99.66, averageYield: 99.66, minYield: 99.66, maxYield: 99.66, tone: "good" },
    { waferIds: ["W09"], stage: "Oxidation", step: "LOX", seq: "seq-num-001", condition: "3600A", weightedYield: 99.73, medianYield: 99.73, averageYield: 99.73, minYield: 99.73, maxYield: 99.73, tone: "good" },
  ],
}

function mapFor(waferId: string) {
  return {
    ...waferMapW01Fixture,
    id: waferId,
    dies: [...waferMapW01Fixture.dies],
  }
}

export const reportWaferMapFixture: ReportWaferMapInput = {
  title: "Wafer Map",
  subtitle: "Report-level wafer grid. Wafer visualization composes shared WaferMap.",
  sourceLabel: "REPORT SNAPSHOT",
  mode: "CP Map",
  layer: "Final Bin",
  wafers: [
    { waferId: "W01", role: "BSL", pass: 4084, fail: 15, defect: 68, tone: "good", map: mapFor("W01") },
    { waferId: "W02", role: "split-1", pass: 4087, fail: 12, defect: 73, tone: "good", map: mapFor("W02") },
    { waferId: "W03", role: "split-2", pass: 319, fail: 3780, defect: 225, tone: "bad", map: mapFor("W03") },
    { waferId: "W10", role: "split-2", pass: 2559, fail: 1540, defect: 148, tone: "watch", map: mapFor("W10") },
  ],
}

export const reportParameterMedianFixture: ReportParameterMedianInput = {
  title: "Parameter Median",
  subtitle: "CP parameter median and CPK matrix by wafer.",
  sourceLabel: "REPORT SNAPSHOT",
  selectedParameterId: "IGSSN1",
  rows: [
    {
      parameter: "IGSSN1",
      unit: "A",
      lsl: -1.71378e-7,
      usl: 1.8671e-7,
      wafers: [
        { waferId: "W01", value: 7.69277e-9, cpk: 2.49, lowYield: false, tone: "good" },
        { waferId: "W02", value: 7.41614e-9, cpk: 2.49, lowYield: false, tone: "good" },
        { waferId: "W03", value: 7.45975e-9, cpk: 1.21, lowYield: true, tone: "bad" },
        { waferId: "W10", value: 8.2242e-9, cpk: 1.44, lowYield: false, tone: "watch" },
        { waferId: "W12", value: 7.9921e-9, cpk: 1.18, lowYield: true, tone: "bad" },
      ],
    },
    {
      parameter: "BVDSS",
      unit: "V",
      lsl: 52.41,
      usl: 127.67,
      wafers: [
        { waferId: "W01", value: 89.59, cpk: 2.37, lowYield: false, tone: "good" },
        { waferId: "W02", value: 91.06, cpk: 2.58, lowYield: false, tone: "good" },
        { waferId: "W03", value: 87.76, cpk: 1.02, lowYield: true, tone: "bad" },
        { waferId: "W10", value: 93.26, cpk: 0.44, lowYield: false, tone: "bad" },
        { waferId: "W12", value: 90.03, cpk: 1.39, lowYield: true, tone: "watch" },
      ],
    },
  ],
}

export const reportCpDataFixture: ReportCpDataInput = {
  title: "CP Data",
  subtitle: "Parent report tab that adapts CP die measurement data into Measurement.",
  sourceLabel: "CP REPORT",
  selectedParameterId: "BVDSS",
  parameterOptions: ["BVDSS", "IGSSN1", "IDSS"],
  measurement: {
    ...measurementFixture,
    title: "Die Measurement Distribution",
    subtitle: "Measurement placeholder composed by Report CP Data.",
    sourceLabel: "MEASUREMENT",
  },
}

export const reportInlineDataFixture: ReportInlineDataInput = {
  title: "Inline Data",
  subtitle: "Parent report tab that adapts inline/SPC data into Measurement.",
  sourceLabel: "INLINE REPORT",
  selectedParameterId: "AMC-SN080724-HDP-NCMP-GOF-69",
  parameterOptions: [
    "AMC-SN080724-HDP-NCMP-GOF-69",
    "AMC-SN080724-HDP-NCMP-TNK-69",
    "AMC-SN080724-PICM-OX-GOF-69",
    "AMC-SN080724-FOX-DEF-BOW-43",
  ],
  measurement: {
    ...measurementFixture,
    title: "Wafer x Inline Parameter",
    subtitle: "Measurement placeholder composed by Report Inline Data.",
    sourceLabel: "MEASUREMENT",
    yAxisLabel: "Inline Parameter Value",
    referenceLines: [
      { label: "USL", value: 0.9, tone: "watch" },
      { label: "Target", value: 0.8, tone: "neutral" },
      { label: "LSL", value: 0.6, tone: "watch" },
    ],
    groups: (measurementFixture.groups ?? []).slice(0, 5).map((group, index) => ({
      ...group,
      values: group.values.map((value) => value / 100),
      mean: group.mean / 100,
      median: group.median / 100,
      low: group.low / 100,
      high: group.high / 100,
      label: ["W01", "W02", "W11", "W18", "W24"][index] ?? group.label,
    })),
  },
}

export const reportCpInlineFixture: ReportCpInlineInput = {
  title: "CP x Inline",
  subtitle: "Condition aggregation and fit-readiness evidence.",
  sourceLabel: "REPORT SNAPSHOT",
  step: "TR CD · BSL + 2 Condition",
  inlineParameter: "AML-SN080724-TR-PH-ADI-69",
  cpParameter: "BVDSS",
  baselineWafers: ["W01", "W11", "W25"],
  splitWafers: ["W02", "W03"],
  rows: [
    {
      stage: "Etch",
      condition: "BSL pooled",
      role: "BSL",
      inlineWafers: "W01 / W11 / W25",
      cpWafers: "W01 / W11 / W25",
      meanInline: 0.782822,
      medianInline: 0.783511,
      meanCp: 89.2337,
      medianCp: 90.0434,
    },
    {
      stage: "Etch",
      condition: "0.75um",
      role: "split-1",
      inlineWafers: "W02",
      cpWafers: "W02",
      meanInline: 0.745379,
      medianInline: 0.745306,
      meanCp: 80.8915,
      medianCp: 91.0559,
    },
    {
      stage: "Etch",
      condition: "0.83um",
      role: "split-2",
      inlineWafers: "W03",
      cpWafers: "W03",
      meanInline: 0.833782,
      medianInline: 0.832165,
      meanCp: 87.5814,
      medianCp: 87.7626,
    },
  ],
}
